import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getBookForHome } from "@/server/action";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const sourceSans3 = localFont({
  src: "./fonts/SourceSans3-VariableFont_wght.ttf",
  variable: "--font-soure-sans-3",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Scanbooky",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const books = await getBookForHome()
  return (
    <html lang="en">
      <body className={`${sourceSans3} ${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
